{
 "title": "Corelight Softsensor Overview",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Active connections",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(corelight_monitor_conns_tcp_active)",
     "legendFormat": "TCP"
    },
    {
     "expr": "sum(corelight_monitor_conns_udp_active) ",
     "legendFormat": "UDP"
    },
    {
     "expr": "sum(corelight_monitor_conns_icmp_active) ",
     "legendFormat": "ICMP"
    }
   ]
  },
  {
   "title": "Suricata Rules",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "corelight_suricata_rules_loaded",
     "legendFormat": "Loaded"
    },
    {
     "expr": "corelight_suricata_rules_failed",
     "legendFormat": "Failed"
    }
   ]
  },
  {
   "title": "Disk Used",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "((corelight_filesystem_size_bytes - corelight_filesystem_avail_bytes) / corelight_filesystem_size_bytes) * 100"
    }
   ]
  },
  {
   "title": "Disk Size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "targets": [
    {
     "expr": "corelight_filesystem_size_bytes"
    }
   ]
  },
  {
   "title": "Data rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(corelight_monitor_pkts_data_bytes_total[$__interval])*8)",
     "legendFormat": "Zeek"
    },
    {
     "expr": "rate(corelight_suricata_pkts_data_bytes_total[$__interval]) * 8  ",
     "legendFormat": "Suricata"
    },
    {
     "expr": "rate(corelight_monitor_pkts_data_bytes_total[$__interval]) * 8  ",
     "legendFormat": "{{process}} rate"
    },
    {
     "expr": "sum(rate(corelight_monitor_pkts_dropped_total[$__interval]))",
     "legendFormat": "Dropped rate"
    }
   ]
  },
  {
   "title": "Mapped Memory Use",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "corelight_memory_mapped_bytes", "legendFormat": "Mapped {{process}}" },
    {
     "expr": "corelight_memory_allocated_bytes",
     "legendFormat": "Allocated {{process}}"
    }
   ]
  },
  {
   "title": "Total Memory Use",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(corelight_memory_allocated_bytes)",
     "legendFormat": "Allocated"
    },
    {
     "expr": "sum(corelight_memory_mapped_bytes)",
     "legendFormat": "Mapped"
    },
    {}
   ]
  },
  {
   "title": "Connection Information",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(corelight_monitor_conns_killed_by_inactivity_total[$__interval])) ",
     "legendFormat": "Killed by Inactivity"
    },
    {
     "expr": "sum(corelight_monitor_conns_fragments)",
     "legendFormat": "Fragments"
    }
   ]
  },
  {
   "title": "New connection rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(corelight_monitor_conns_tcp_total[$__interval])) by (job)",
     "legendFormat": "TCP"
    },
    {
     "expr": "sum(rate(corelight_monitor_conns_udp_total[$__interval])) by (job)",
     "legendFormat": "UDP"
    },
    {
     "expr": "sum(rate(corelight_monitor_conns_icmp_total[$__interval])) by (job)",
     "legendFormat": "ICMP"
    }
   ]
  },
  {
   "title": "Disk used",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "corelight_filesystem_usage_ratio",
     "legendFormat": "{{job}} disk used"
    }
   ]
  }
 ]
}